### ISSUE TITLE
Why is 0 the reverse of 1534236469

### ISSUE THREAD

**Issue by sifatul** [Sifatul/leetCode#2]
### [Reverse Integer](https://leetcode.com/problems/reverse-integer/submissions/) [Easy]

How come the output is 0 instead of 1056389759 after reversing 1534236469??

Screenshot:

![image](https://user-images.githubusercontent.com/10746740/90767375-147aa380-e328-11ea-98c4-622d971fbc55.png)

**Comment by sifatul** [comment]
the question requires the output to be 0 when the result overflow Thus as 1534236469 overflows  `Integer.MAX_VALUE` the output is 0;

**Comment by MythicalMayhem** [comment]
the reverse number of 1534236469 is 9646324351 which is not a 32 bit integer

ps : 
      - a 32bit integer should be less than 4,294,967,296 which is (2^32)
